linters-settings:
  dupl:
    threshold: 200
  funlen:
    lines: -1
    statements: 150
  gci:
    skip-generated: true
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/zc2638/ink)
      - blank
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    settings:
      ifElseChain:
        minThreshold: 3
  gocyclo:
    min-complexity: 35
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
  goimports:
    local-prefixes: github.com/zc2638/ink
  govet:
    check-shadowing: false
  gosec:
    excludes:
      - G204
  lll:
    line-length: 160
  misspell:
    locale: US
    ignore-words:
      - sanitised
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  revive:
    rules:
      - name: unexported-return
        disabled: true
      - name: unused-parameter
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - funlen
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  # don't enable:
  # - asciicheck
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - wsl

run:
  timeout: 10m
  issues-exit-code: 1
  skip-dirs:
    - build
    - config
    - resource/database
    - test/e2e/project
    - testdata
