name: Main WorkFlow
on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: go get -v -t -d ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Test
        run: make test

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: make build
